

export const FETCH_MENUS = 'FETCH_MENUS'  ; 
export const FETCH_MENUS_SUCCESS = 'FETCH_MENUS_SUCCESS'  ; 
export const FETCH_MENUS_FAILED = 'FETCH_MENUS_FAILED'  ; 



//   comments 

export const FETCH_COMMENTS = 'FETCH_COMMENTS'  ; 
export const FETCH_APPROVED_COMMENTS_SUCCESS = 'FETCH_APPROVED_COMMENTS_SUCCESS'  ; 
export const FETCH_DISAPPROVED_COMMENTS_SUCCESS = 'FETCH_DISAPPROVED_COMMENTS_SUCCESS'  ; 

export const FETCH_COMMENTS_FAILED = 'FETCH_COMMENTS_FAILED'  ; 


// category 

export const FETCH_CATEGORY = 'FETCH_CATEGORY'  ; 
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'  ; 
export const FETCH_CATEGORY_FAILED = 'FETCH_CATEGORY_FAILED'  ; 

// courses

export const FETCH_COURSES = 'FETCH_COURSES'  ; 
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS'  ; 
export const FETCH_COURSES_FAILED = 'FETCH_COURSES_FAILED'  ; 



//Epsiodes

export const FETCH_EPISODE = 'FETCH_EPISODE'  ; 
export const FETCH_EPISODE_SUCCESS = 'FETCH_EPISODE_SUCCESS'  ; 
export const FETCH_EPISODE_FAILED = 'FETCH_EPISODE_FAILED'  ; 


